version: "1"
rules:                           # Array of rules
  - base: template               # Required. Target branch
    upstream: ublue-os:template  # Required. Must be in the same fork network.
    mergeMethod: hardreset       # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false
  - base: live                   # Required. Target branch
    upstream: template           # Required. Must be in the same fork network.
    mergeMethod: merge           # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"