title: Welcome to Makerspace Kinoite
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Makerspace Kinoite (Alpha)"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system! We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub. If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  create-makerspace-account:
    source: yafti.screen.consent
    values:
      title: Setup Makerspace account!
      # condition:
      #   run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the Makerspace account is missing.
      actions:
        - run: grep -E '^dialout:' /usr/lib/group >> /etc/group
        - run: grep -E '^users:' /usr/lib/group >> /etc/group
        - run: groupadd -r nopasswdlogin
        - run: adduser -mG nopasswdlogin,dialout,users -c "Maker Space" makerspace
        - run: cp /usr/share/plasma/avatars/photos/Pencils.png /var/lib/AccountsService/icons/makerspace
        - run: echo "[User]" | tee /var/lib/AccountsService/users/makerspace
        - run: echo "Icon=/var/lib/AccountsService/icons/makerspace" | tee -a /var/lib/AccountsService/users/makerspace
        - run: kwriteconfig5 --file /usr/etc/sddm.conf --group Autologin --key User makerspace 
        - run: kwriteconfig5 --file /usr/etc/sddm.conf --group Autologin --key Session plasmax11.desktop 
        - run: kwriteconfig5 --file /usr/etc/sddm.conf --group General --key DisplayServer x11 
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Mozilla Firefox: org.mozilla.firefox
            - Breeze Theme: org.gtk.Gtk3theme.Breeze
            - Gwenview: org.kde.gwenview
            - Okular: org.kde.okular
            - VLC: org.videolan.VLC
        Office Apps:
          description: Office applications.
          default: true
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
        CAD/CAM Apps:
          description: Makerspace applications.
          default: true
          packages:
            - Inkscape: org.inkscape.Inkscape
            - Blender: org.blender.Blender
            - FreeCAD: org.freecadweb.FreeCAD
            - LibreCAD: org.librecad.librecad
            - OpenSCAD: org.openscad.OpenSCAD
            - PrusaSlicer: com.prusa3d.PrusaSlicer
        Developer Apps:
          description: Software Development applications.
          default: true
          packages:
            - VSCodium: com.vscodium.codium
            - Arduino2: cc.arduino.IDE2
            - RPi Imager: org.raspberrypi.rpi-imager
  set-flatpak-defaults:
    source: yafti.screen.consent
    values:
      title: Setup flatpak defaults!
      # condition:
      #   run: flatpak remotes --columns=name | grep fedora
      description: |
        Set Flatpak defaults.
      actions:
        - run: flatpak override --env=PRUSA_SLICER_DARK_THEME=true com.prusa3d.PrusaSlicer
        - run: flatpak override --env=GTK_THEME=Adwaita:dark
        #- run: 
        #- run: 
        #- run: 
        #- run: 
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/plasma-discover
        - "Website":
            run: /usr/bin/xdg-open https://Makerspace Kinoite.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying Makerspace Kinoite, we hope you enjoy it!
